export const IMPORTANT_EVENTS = {
  ORDER_CREATED: { category: "order", importance: "high" },
  ORDER_CONFIRMED: { category: "order", importance: "high" },
  ORDER_SHIPPED: { category: "order", importance: "normal" },
  ORDER_OUT_FOR_DELIVERY: { category: "order", importance: "normal" },
  ORDER_DELIVERED: { category: "order", importance: "high" },
  ORDER_CANCELLED: { category: "order", importance: "critical" },
  ORDER_RETURN_REQUESTED: { category: "order", importance: "high" },
  ORDER_REFUNDED: { category: "order", importance: "high" },
  ORDER_TIMEOUT: { category: "order", importance: "high" },
  LOW_STOCK: { category: "inventory", importance: "high" },
  OUT_OF_STOCK: { category: "inventory", importance: "critical" },
  STOCK_RESTORED: { category: "inventory", importance: "normal" },
  INVENTORY_PUBLISHED: { category: "inventory", importance: "low" },
  PRICE_DROP: { category: "pricing", importance: "normal" },
  PRICE_APPROVED: { category: "pricing", importance: "high" },
  COUPON_CREATED: { category: "pricing", importance: "normal" },
  CHAT_MESSAGE: { category: "chat", importance: "low" },
  CHAT_ASSIGNED: { category: "chat", importance: "normal" },
  CHAT_ESCALATED: { category: "chat", importance: "high" },
  GLOBAL_ANNOUNCEMENT: { category: "cms", importance: "normal" },
  ACCOUNT_LOGIN: { category: "auth", importance: "low" },
  ACCOUNT_LOGIN_FAILED: { category: "auth", importance: "high" },
  ACCOUNT_LOCKED: { category: "auth", importance: "critical" },
  ACCOUNT_CREATED: { category: "auth", importance: "normal" },
  TENANT_SUSPENDED: { category: "tenant", importance: "critical" },
  PRODUCT_PUBLISHED: { category: "catalog", importance: "normal" },
  CMS_PUBLISHED: { category: "cms", importance: "normal" },
};

export const ANALYTICS_CATEGORIES = [
  "order",
  "inventory",
  "pricing",
  "chat",
  "auth",
  "tenant",
  "catalog",
  "cms",
  "account",
];
